"""Reverse index: Latin (Sing Khmer) spelling -> ranked Khmer candidates (step 1.6).

This is the actual runtime lookup table. It is built from two sources:

- **collected** — every romanization the team entered for a word maps to that word.
  This is ground truth and the backbone of the engine (it captures whole-word
  abbreviations like ``nh`` -> ខ្ញុំ that don't decompose into syllables).
- **generated** — for words whose syllables (KCCs) all have phonetic rules, the
  Cartesian product of the per-KCC spellings yields extra plausible spellings the
  team never typed. This is the generalization layer (lower score than collected).

A single spelling can map to several Khmer words (homophones), so each key holds a
list of candidates ranked by score (word frequency, collected before generated).
"""

from __future__ import annotations

import itertools
from collections import defaultdict
from dataclasses import dataclass

from .kcc import segment
from .phonetic_rules import Rule
from .vocabulary import VocabEntry


@dataclass(frozen=True)
class Candidate:
    """One Khmer word suggested for a Latin spelling."""

    khmer: str
    score: float
    source: str          # "collected" or "generated"


def _norm(text: str) -> str:
    return text.strip().lower()


def _generated_keys(
    entry: VocabEntry, rules: dict[str, list[Rule]], *, top_per_kcc: int, cap: int
) -> list[tuple[str, float]]:
    """Spellings generated by combining each KCC's rule spellings. Empty if any
    KCC of the word has no rule (we only generate when the whole word is covered)."""
    options: list[list[tuple[str, float]]] = []
    for k in segment(entry.khmer):
        rs = rules.get(k)
        if not rs:
            return []
        options.append([(r.spelling, r.weight) for r in rs[:top_per_kcc]])

    out: list[tuple[str, float]] = []
    for combo in itertools.product(*options):
        key = "".join(sp for sp, _ in combo)
        weight = 1.0
        for _, w in combo:
            weight *= w
        out.append((key, weight))
        if len(out) >= cap:
            break
    return out


def build_index(
    vocab: list[VocabEntry],
    rules: dict[str, list[Rule]] | None = None,
    *,
    top_per_kcc: int = 3,
    max_generated_per_word: int = 20,
) -> dict[str, list[Candidate]]:
    """Build the reverse index mapping a normalized spelling to ranked candidates.

    Args:
        vocab: loaded vocabulary.
        rules: optional phonetic rules; when given, adds the generated layer.
        top_per_kcc: how many spellings per KCC to combine when generating.
        max_generated_per_word: cap on generated spellings per word (avoids blow-up).
    """
    # key -> khmer -> (best_score, source)
    acc: dict[str, dict[str, tuple[float, str]]] = defaultdict(dict)

    def add(key: str, khmer: str, score: float, source: str) -> None:
        key = _norm(key)
        if not key:
            return
        cur = acc[key].get(khmer)
        if cur is None or score > cur[0]:
            acc[key][khmer] = (score, source)

    # collected (backbone)
    for e in vocab:
        for r in e.romanizations:
            add(r, e.khmer, float(e.frequency), "collected")

    # generated (generalization layer)
    if rules:
        for e in vocab:
            for key, weight in _generated_keys(
                e, rules, top_per_kcc=top_per_kcc, cap=max_generated_per_word
            ):
                # generated always scores below a collected hit of the same word
                add(key, e.khmer, float(e.frequency) * weight * 0.99, "generated")

    # finalize: ranked candidate lists
    index: dict[str, list[Candidate]] = {}
    for key, by_khmer in acc.items():
        cands = [Candidate(k, round(s, 3), src) for k, (s, src) in by_khmer.items()]
        cands.sort(key=lambda c: (-c.score, c.source != "collected", c.khmer))
        index[key] = cands
    return index
